### ISSUE TITLE
Version 2 breaking changes

### ISSUE THREAD

**Issue by lpellegr** [vaadin/router#898]
I am trying to upgrade to version 2 but I am facing many issues.

Here is an idea of the errors I am getting in a real project using Typescript _5.6.3_:

``` 
[tsc] node_modules/@vaadin/router/dist/resolver/resolver.d.ts(11,49): error TS2304: Cannot find name 'ErrorOptions'.
[tsc] src/design-system/noticeable-project-upsert.ts(90,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/design-system/noticeable-project-upsert.ts(90,39): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/design-system/noticeable-project-upsert.ts(90,78): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/design-system/noticeable-project-upsert.ts(90,101): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-app.ts(90,16): error TS2540: Cannot assign to 'baseUrl' because it is a read-only property.
[tsc] src/pages/noticeable-organization-api.ts(54,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organization-api.ts(54,54): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organization-integration-sso-connection-upsert.ts(72,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organization-integration-sso-connection-upsert.ts(72,39): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organization-integration-sso-connection-upsert.ts(72,78): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organization-integration-sso-connection-upsert.ts(72,101): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organization-owners.ts(50,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organization-owners.ts(50,54): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organization-token-upsert.ts(63,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organization-token-upsert.ts(63,54): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organizations-list.ts(45,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-organizations-list.ts(45,54): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-project-collaborators.ts(50,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-project-collaborators.ts(50,54): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-project-publication-edit.ts(123,63): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-project-publication-edit.ts(123,86): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-project-publication-edit.ts(123,125): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-project-publication-edit.ts(123,148): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-project-widgets.ts(68,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-project-widgets.ts(68,54): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-signin.ts(179,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/noticeable-signin.ts(179,54): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/page-view.ts(2,5): error TS2305: Module '"@vaadin/router"' has no exported member 'AfterEnterObserver'.
[tsc] src/pages/page-view.ts(3,5): error TS2305: Module '"@vaadin/router"' has no exported member 'AfterLeaveObserver'.
[tsc] src/pages/page-view.ts(4,5): error TS2305: Module '"@vaadin/router"' has no exported member 'BeforeEnterObserver'.
[tsc] src/pages/page-view.ts(5,5): error TS2305: Module '"@vaadin/router"' has no exported member 'BeforeLeaveObserver'.
[tsc] src/pages/page-view.ts(23,46): error TS1172: 'extends' clause already seen.
[tsc] src/pages/page-view.ts(171,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/page-view.ts(171,39): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/page-view.ts(171,78): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/page-view.ts(171,101): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/page-view.ts(175,16): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
[tsc] src/pages/page-view.ts(175,54): error TS2702: 'Router' only refers to a type, but is being used as a namespace here.
``` 

It seems there is no release notes. I am fighting trying to understand the changes? Are you going to publish a release note/changelog?

In version 1, there were interfaces for _AfterEnterObserver_, _AfterLeaveObserver_, etc. exported from ` @vaadin/router` and that could be implemented in our own classes. It seems no longer the case. The following errors:

``` 
import {
    AfterEnterObserver,
    AfterLeaveObserver,
    BeforeEnterObserver,
    BeforeLeaveObserver,
} from '@vaadin/router';

export class PageView extends StoreConnector implements AfterEnterObserver, AfterLeaveObserver, BeforeEnterObserver, BeforeLeaveObserver {
}
``` 

What is the replacement?

Same for types `Router.PreventResult`, `Router.RedirectResult`. They seem no longer exported. 

Also, `router.baseUrl` is now read-only. How to change its value? previously it was possible to do something like:

``` 
const router = new Router(document.querySelector('noticeable-app'));
router.baseUrl = '/';
router.setRoutes(routes);
``` 

The project referenced link on Github is broken:
https://hilla.dev/docs/routing/router

**Comment by lpellegr** [comment]
I succeeded to resolve the compilation errors looking at the project source code. Demos are no longer available.

Base URL can be set by passing an argument object to the Router constructor: `const router = new Router(document.querySelector('noticeable-app'), {baseUrl: '/'});`.

It looks like action observer interfaces have been removed. What is the reason? they were really convenient. Instead, we need to implement _WebComponentInterface_ with new typings. Even the tests in the router project lack information for the generic types of _WebComponentInterface_...

`ErrorOptions` requires ES2022.

Once type errors are resolved, I am still getting an error at runtime:

> Uncaught (in promise) TypeError: Can not repeat "0" without a prefix and suffix
>     at tokensToRegexp (index.js:372:31)
>     at stringToRegexp (index.js:338:12)
>     at pathToRegexp (index.js:413:12)
>     at matchPath (matchPath.js:23:16)
>     at Object.next (matchRoute.js:23:17)
>     at Object.next (matchRoute.js:52:43)
>     at Object.next (resolver.js:162:38)
>     at findNextContextIfAny (router.js:352:42)
>     at #fullyResolveChain (router.js:363:31)
>     at async #doRender (router.js:283:32)
> await in #fullyResolveChain		
> initRouter	@	noticeable-app.ts:90
> firstUpdated	@	noticeable-app.ts:105

I suspect this is related to how routes are defined.

**Comment by lpellegr** [comment]
The error `Can not repeat "0" without a prefix and suffix` was caused by a route path:

> path: '(.*)+'

I see the version of _path-to-regex_ was updated with version 2 of _vaadin-router_. It looks like this new version of _path-to-regex_ is stricter. Using the following route path solves the issue:

> path: '(.*)'

**Comment by ajcool2k** [comment]
@lpellegr 

I found this compat file that was added a few minutes ago:

https://github.com/vaadin/router/blob/main/src/v1-compat.t.ts

This likely will restore the old interfaces with deprecation

```
export interface AfterEnterObserver {
  /**
   * See {@link WebComponentInterface.onAfterEnter}
   */
  onAfterEnter: NonNullable<WebComponentInterface['onAfterEnter']>;
}
```

So it looks like you could use the new api by importing `WebComponentInterface` and implement it. It will hold the event handlers directly.
